# Generated by Django 2.2 on 2019-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('blackListed', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='pics/')),
                ('friendsWith', models.CharField(max_length=250)),
                ('ageWhenEntered', models.IntegerField()),
                ('notes', models.TextField()),
                ('dateEntered', models.DateTimeField()),
            ],
        ),
    ]
