# Generated by Django 2.2.5 on 2019-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='encoding',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
